#!/usr/bin/env python3

import sys
import os
from drop_mongodb_database import drop_mongodb_database
from utils import pip_install, execute_bash
from dotenv import load_dotenv

app_name=sys.argv[1] if len(sys.argv) >1 else None

if __name__ == "__main__":
    pip_install("python-dotenv")
    load_dotenv()
    original = app_name.split("-pr-")
    if len(original)> 1:
        original_app_name = original[0]
        command = f"dokku config:get {original_app_name} MONGODB_URL"
        mongodb_url = execute_bash(command)
        if mongodb_url:
            drop_mongodb_database(mongodb_url, app_name)
        