#!/usr/bin/env bash

mongodb_base_url="https://fastdl.mongodb.org/tools/db"

# Specify the directory where you want to install the tools
install_directory="/usr/local/bin"
# Get Distributor ID and Release number
curl -s http://httpbin.org/get | grep "cwd" | awk -F '"' '{print $4}'
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
sudo apt-get update
sudo apt-get install -y mongodb-org
