#!/usr/bin/env bash

mongodb_base_url="https://fastdl.mongodb.org/tools/db"

# Specify the directory where you want to install the tools
install_directory="/usr/local/bin"
# Get Distributor ID and Release number
distro=$(lsb_release -si | awk '{print tolower($0)}')
release=$(lsb_release -sr | tr -d '.')

# Get architecture
arch=$(echo "$(uname -m)" | sed 's/arch/arm/g')
# Concatenate Distributor ID, Release number, and architecture
echo "${distro}${release}-${arch}"
download_file="mongodb-database-tools-${distro}${release}-${arch}-100.8.0.tgz"

curl -O "${mongodb_base_url}/${download_file}"
echo "${mongodb_base_url}/${download_file}"

tar -xzf ${download_file}
mv "mongodb-database-tools-${distro}${release}-${arch}-100.8.0/bin/"* "$install_directory"

# Clean up the downloaded files
rm -rf "mongodb-database-tools-${distro}${release}-${arch}-100.8.0" ${download_file}
echo "MongoDB tools installed to ${install_directory}"
